name: 'Setup Playwright With Cache'
description: 'Setup Playwright With Cache'
inputs:
  working-directory:
    description: 'Working directory'
runs:
  using: "composite"
  steps:
    - name: Store Playwright's Version
      id: store-playwright-version
      run: |
        PLAYWRIGHT_VERSION=$(yarn info @playwright/test | grep "Version:" | sed 's/.*\: //')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ steps.store-playwright-version.outputs.PLAYWRIGHT_VERSION }}
    - name: Setup Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: yarn playwright install --with-deps
      shell: bash
      working-directory: ${{ inputs.working-directory }}
